### PR TITLE
[radius/models] Use UUID or natural keys #97

### LINKED ISSUE #97: [radius/models] Use UUID or natural keys
Some objects, like the accounting object, have keys which can be used as natural primary keys (eg: session ID or unique accounting ID), but we need to double check if this is ok.

In other objects, we could just switch to UUID.

I don't want to rely on auto-increment IDs.

### PR DESCRIPTION
**Pull request by NoumbissiValere**
Fixed the issue by replacing primary keys with
natural keys or UUID in case there was no
possible natural key

Fixes #97

### CODE REVIEW

**Comment by NoumbissiValere** [comment]
@nemesisdesign please can you review this?

**Comment by NoumbissiValere** [comment]
Thanks for reviewing

**Comment by atb00ker** [comment]
@NoumbissiValere there is a conflict. :smile:

**Comment by NoumbissiValere** [comment]
@atb00ker will fix it. Thanks :smile:

**Comment by NoumbissiValere** [comment]
@atb00ker conflict resolved :blush:

**Pull request merged**
