### PR TITLE
[change] Make email lowercase during registration #224

### LINKED ISSUE #224: [change] Make email lowercase during registration
Let's avoid the possibility of having multiple users with the same email but with different cases for letters.

We should edit the register serializer to ensure the email is converted to lowercase (+ unit test).

### PR DESCRIPTION
**Pull request by sankha555**
Added validation in RegisterSerializer to convert email to lowercase during registration. A unit test has also been added to test the same.

Fixes #224

### CODE REVIEW

**Comment by sankha555** [comment]
Closing this PR due to accumulation of multiple commits with erraneous and conflicting code. Opened PR #225 .

**Comment by sankha555** [comment]
@nemesisdesign I have made the required changes in this PR and have added some comments to explain the change in the serializer. Please take a look at them and suggest any required changes. Thanks!

**Comment by atb00ker** [comment]
This issue has been moved to openwisp-users, read here: https://github.com/openwisp/openwisp-users/issues/227
Let's continue the conversation there! :smile:

**Comment by nemesisdesign** [comment]
@sankha555 can you move the solution to openwisp-user by adding a few lines in the user model validation code and the relative test there?

**Pull request closed without merging**
