### PR TITLE
[deps] Drop support for Django 2.2 #171

### LINKED ISSUE #171: [deps] Drop support for Django 2.2
Drop support for Django 2.2 and remove any compatibility shims for that version in the repository.

### PR DESCRIPTION
**Pull request by tullur**
Remove Django 2.2 from requirements and travis.

Closes #171

### CODE REVIEW

**Review by nemesisdesign — APPROVED** [review]
Approved, thank you!
Will wait to merge until the current version is released. The version after this one will be django>3.0 only.

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
This code has to be removed, could you update the PR? @tullur 

- https://github.com/openwisp/openwisp-radius/commit/65201402eb696e8d821d5e9d966efe159e4d303e#diff-853278c623903efdd3f9c592e6effbe08a48801e4a6c471780cd2eac499eaa32R2602-R2604

**Comment by tullur** [comment]
Hey @nemesisdesign, rebased on current master branch.

**Review by nemesisdesign — APPROVED** [review]
Thanks! I'll wait a bit more before merging,

**Comment by atb00ker** [comment]
@nemesisdesign do we want to drop Django 2.2? It's LTS and supported for atleast one more year.
[Check django release cycle](https://endoflife.date/django).

**Comment by nemesisdesign** [comment]
> @nemesisdesign do we want to drop Django 2.2? It's LTS and supported for atleast one more year.
> [Check django release cycle](https://endoflife.date/django).

@atb00ker I know the django release cycle. First of all, the active support has already ended, only security support is maintained, which means they only patch django 2.2 for security issues, not regular features.

Moreover some of the new features of OpenWISP require at least django > 3.0, supporting multiple django versions costs too much resources and we'd better invest those resources in growing OpenWISP rather than supporting old django versions, keep in mind the majority of users of OpenWISP care about managing and deploying their networks, they do not care about django 2.2. 
Our installers automatically install the latest django version so it's not a problem for us.

If anybody needs django 2.2, the cost of maintaining the modules must be on them, not on us.

**Pull request merged**
