### PR TITLE
Add unit test for batch creation operation performed via API

### LINKED ISSUE #27: [batch] Add unit test for batch creation operation performed via API
A unit test should check that the API view of the batch user creation operation assigns created users to the right organization.

### PR DESCRIPTION
**Pull request by Vivekrajput20**
Closes #27

### CODE REVIEW

**Comment by Vivekrajput20** [comment]
@atb00ker @nemesisdesign can you please review it and tell if anything else needs to be done on the issue?

**Comment by atb00ker** [comment]
@Vivekrajput20 Can you please add `Closes #27` in your commit so that other people can know about the active pull request from the issue?

Thanks

**Comment by atb00ker** [comment]
Hi again, try this commit message:
```
Add unit test for batch creation operation performed via API #27

Closes #27
```

The `Closes #27` line is used by GitHub for automation of issues and the first line is the commit message to ensure that everyone understands what's in the commit.

I hope i've made the format clear now, thanks! :+1:

**Comment by Vivekrajput20** [comment]
@atb00ker I've updated the commit message

**Comment by nemesisdesign** [comment]
Many thanks to @atb00ker for reviewing the PR too! :+1:

**Pull request merged**
